// Code generated by mockery. DO NOT EDIT.

package mockmember

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRoleAssigner is an autogenerated mock type for the RoleAssigner type
type MockRoleAssigner struct {
	mock.Mock
}

type MockRoleAssigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleAssigner) EXPECT() *MockRoleAssigner_Expecter {
	return &MockRoleAssigner_Expecter{mock: &_m.Mock}
}

// AssignRole provides a mock function with given fields: ctx, guildID, userID, roleID
func (_m *MockRoleAssigner) AssignRole(ctx context.Context, guildID string, userID string, roleID string) error {
	ret := _m.Called(ctx, guildID, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, guildID, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleAssigner_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type MockRoleAssigner_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
//   - userID string
//   - roleID string
func (_e *MockRoleAssigner_Expecter) AssignRole(ctx interface{}, guildID interface{}, userID interface{}, roleID interface{}) *MockRoleAssigner_AssignRole_Call {
	return &MockRoleAssigner_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, guildID, userID, roleID)}
}

func (_c *MockRoleAssigner_AssignRole_Call) Run(run func(ctx context.Context, guildID string, userID string, roleID string)) *MockRoleAssigner_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRoleAssigner_AssignRole_Call) Return(_a0 error) *MockRoleAssigner_AssignRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleAssigner_AssignRole_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockRoleAssigner_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleAssigner creates a new instance of MockRoleAssigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleAssigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleAssigner {
	mock := &MockRoleAssigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
