with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/ak1m1tsu/barman/internal/domain/guild:
    config:
      dir: "mocks/guild"
      outpkg: "mockguild"
    interfaces:
      Repository:
  github.com/ak1m1tsu/barman/internal/usecase/member:
    config:
      dir: "mocks/member"
      outpkg: "mockmember"
    interfaces:
      RoleAssigner:
  github.com/ak1m1tsu/barman/internal/usecase/reaction:
    config:
      dir: "mocks/reaction"
      outpkg: "mockreaction"
    interfaces:
      GIFFetcher:
  github.com/ak1m1tsu/barman/internal/domain/reaction:
    config:
      dir: "mocks/reaction"
      outpkg: "mockreaction"
    interfaces:
      StatsRepository:
