// Code generated by mockery. DO NOT EDIT.

package mockreaction

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGIFFetcher is an autogenerated mock type for the GIFFetcher type
type MockGIFFetcher struct {
	mock.Mock
}

type MockGIFFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGIFFetcher) EXPECT() *MockGIFFetcher_Expecter {
	return &MockGIFFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, reaction
func (_m *MockGIFFetcher) Fetch(ctx context.Context, reaction string) (string, error) {
	ret := _m.Called(ctx, reaction)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, reaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, reaction)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGIFFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockGIFFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - reaction string
func (_e *MockGIFFetcher_Expecter) Fetch(ctx interface{}, reaction interface{}) *MockGIFFetcher_Fetch_Call {
	return &MockGIFFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, reaction)}
}

func (_c *MockGIFFetcher_Fetch_Call) Run(run func(ctx context.Context, reaction string)) *MockGIFFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGIFFetcher_Fetch_Call) Return(_a0 string, _a1 error) *MockGIFFetcher_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGIFFetcher_Fetch_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockGIFFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGIFFetcher creates a new instance of MockGIFFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGIFFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGIFFetcher {
	mock := &MockGIFFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
