// Code generated by mockery. DO NOT EDIT.

package mockreaction

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStatsRepository is an autogenerated mock type for the StatsRepository type
type MockStatsRepository struct {
	mock.Mock
}

type MockStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsRepository) EXPECT() *MockStatsRepository_Expecter {
	return &MockStatsRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockStatsRepository) GetAll(ctx context.Context) (map[string]int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockStatsRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsRepository_Expecter) GetAll(ctx interface{}) *MockStatsRepository_GetAll_Call {
	return &MockStatsRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockStatsRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockStatsRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStatsRepository_GetAll_Call) Return(_a0 map[string]int64, _a1 error) *MockStatsRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsRepository_GetAll_Call) RunAndReturn(run func(context.Context) (map[string]int64, error)) *MockStatsRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: ctx, reactionType
func (_m *MockStatsRepository) Increment(ctx context.Context, reactionType string) error {
	ret := _m.Called(ctx, reactionType)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, reactionType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStatsRepository_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockStatsRepository_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - reactionType string
func (_e *MockStatsRepository_Expecter) Increment(ctx interface{}, reactionType interface{}) *MockStatsRepository_Increment_Call {
	return &MockStatsRepository_Increment_Call{Call: _e.mock.On("Increment", ctx, reactionType)}
}

func (_c *MockStatsRepository_Increment_Call) Run(run func(ctx context.Context, reactionType string)) *MockStatsRepository_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStatsRepository_Increment_Call) Return(_a0 error) *MockStatsRepository_Increment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatsRepository_Increment_Call) RunAndReturn(run func(context.Context, string) error) *MockStatsRepository_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsRepository creates a new instance of MockStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsRepository {
	mock := &MockStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
